"""empty message

Revision ID: 9fd61409a976
Revises: eccdc07d97b7
Create Date: 2023-12-04 18:27:04.433921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd61409a976'
down_revision = 'eccdc07d97b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gallery_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'gallery', ['gallery_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('gall_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gall_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'gallery', ['gall_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('gallery_id')

    # ### end Alembic commands ###
